version: '3.5'


networks:
  inception: {}

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb
    networks:
      - inception
    volumes:
      - mariadb_v:/var/lib/mysql
    restart: always

volumes:
  mariadb_v:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/tblaase/data/mariadb
